---
title: "First Knit"
author: "Liberty Montez"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended Eastside High School and graduated class of 2023, English is something much easier for me because I am able to write for long periods of time while math is a little more difficult for me. The subject I personally do my best in is biology because its something that mostly interests me.   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  The computer I currently have and am using for this class is an Apple laptop, From a scale of 1 to 10 on how well I am with computer stuff I personally would rate myself a 7 because I know the basics but I am not the best at understanding how a computer works. I do have access to internet the connection to the internet to where I like works really well.   
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  I personally would like to be called by my first name Liberty because it is the name I know best and almost everyone calls me by my first name. So I would like this class and my instructor to call me by my first name Liberty.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  In life, I want to achieve my Associate's degree in nursing and eventually become a labor and delivery nurse through the Navy. The college subject that would be of the greatest interest to me would be biology, The degree I am currently trying to get my associate's degree in nursing.  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  I have never gone to any foreign countries but in the future, I would really like to go to China, Russia, Australia, and the Bahamas. I have never been in the military before I actually am thinking of going into the Navy so if I had to choose which branch I would draft into it would be the Navy because I feel like I would learn a lot and be in many different environments and situations that would help me grow as a person.    
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
 I have not taken Math 115 or 116 until now, no I did not know that Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions but now I do know. The grade I need to attain in statistics, to not upset any of my future plans would be to have an A+ my plan is to get into the nursing program here at Antelope Valley College.  
   
 






  




